name_mapping = {
    # MYTHICS
    'madara': 'Modoro_(Madara)',
    'modoro': 'Modoro_(Madara)',
    'shade': 'Shade_(Cid_Kagenou)',
    'cid': 'Shade_(Cid_Kagenou)',
    'cid kagenou': 'Shade_(Cid_Kagenou)',
    'kagenou': 'Shade_(Cid_Kagenou)',
    'sakuya': 'Time_Maid_(Sakuya)',
    'time maid': 'Time_Maid_(Sakuya)',
    'rengogo': 'Rengogo_(Rengoku)',
    'rengoku': 'Rengogo_(Rengoku)',
    'whitebeard': 'White_Moustache_(Whitebeard)',
    'white moustache': 'White_Moustache_(Whitebeard)',
    'broccoli': 'Broly',
    'broly': 'Broly',
    'rimuru': 'Slime_Lord_(Rimuru)',
    'slime lord': 'Slime_Lord_(Rimuru)',
    'mob': 'Helmet_(Mob)',
    'helmet': 'Helmet_(Mob)',
    'gojo': 'Gogo_(Gojo)',
    'gogo': 'Gogo_(Gojo)',
    'guts': 'Struggler_(Guts)',
    'struggler': 'Struggler_(Guts)',
    'yuta': 'Cursed_Boy_(Yuta)',
    'cursed boy': 'Cursed_Boy_(Yuta)',
    'sukuna': 'Skuno_(Sukuna)',
    'skuno': 'Skuno_(Sukuna)',
    'toji': 'Taji_(Toji)',
    'taji': 'Taji_(Toji)',
    'geto': 'Gitu_(Geto)',
    'gitu': 'Gitu_(Geto)',
    'choi': 'Joi_(Choi)',
    'joi': 'Joi_(Choi)',
    'sung': 'Solo_Gamer_(Sung_Jin-woo)',
    'sung jin-woo': 'Solo_Gamer_(Sung_Jin-woo)',
    'jin-woo': 'Solo_Gamer_(Sung_Jin-woo)',
    'solo gamer': 'Solo_Gamer_(Sung_Jin-woo)',
    'megumi': 'Potential_Man',
    'fushiguro': 'Potential_Man',
    'megumi fushiguro': 'Potential_Man',
    'potential man': 'Potential_Man',
    'cha hae-in': 'Chair_(Cha_Hae-In)',
    'cha': 'Chair_(Cha_Hae-In)',
    'hae-in': 'Chair_(Cha_Hae-In)',
    'hae in': 'Chair_(Cha_Hae-In)',
    'chair': 'Chair_(Cha_Hae-In)',
    'tommy': 'Tommy_(Thomas_Andre)',
    'thomas andre': 'Tommy_(Thomas_Andre)',
    'thomas': 'Tommy_(Thomas_Andre)',
    'andre': 'Tommy_(Thomas_Andre)',
    # LEGENDARIES
    'darth vader': 'Dark_Invader_(Darth_Vader)',
    'darth': 'Dark_Invader_(Darth_Vader)',
    'vader': 'Dark_Invader_(Darth_Vader)',
    'dark invader': 'Dark_Invader_(Darth_Vader)',
    'todo': 'Clapman_(Todo)',
    'clapman': 'Clapman_(Todo)',
    'dio': 'DEO_(DIO)',
    'deo': 'DEO_(DIO)',
    'bulma': 'Boulmi_(Bulma)',
    'boulmi': 'Boulmi_(Bulma)',
    'steve': 'Bob_(Steve)',
    'bob': 'Bob_(Steve)',
    'shinobu': 'Butterfly_(Shinobu)',
    'butterfly': 'Butterfly_(Shinobu)',
    'all might': 'EveryMight_(All_Might)',
    'every might': 'EveryMight_(All_Might)',
    'byakuya': 'Byakari_(Byakuya)',
    'byakari': 'Byakari_(Byakuya)',
    # EPICS
    'batman': 'Dark_Knight_(Batman)',
    'dark knight': 'Dark_Knight_(Batman)',
    'jotaro': 'Joe_(Jotaro)',
    'joe': 'Joe_(Jotaro)',
    'harry potter': 'Henry_(Harry_Potter)',
    'harry': 'Henry_(Harry_Potter)',
    'potter': 'Henry_(Harry_Potter)',
    'henry': 'Henry_(Harry_Potter)',
    'eren': 'Eric_(Eren)',
    'eric': 'Eric_(Eren)',
    'nanami': 'Nomnomi_(Nanami)',
    'nomnomi': 'Nomnomi_(Nanami)',
    'ichigo': 'Ichytoe_(Ichigo)',
    'ichytoe': 'Ichytoe_(Ichigo)',
    'sakura': 'Blossom_(Sakura)',
    'blossom': 'Blossom_(Sakura)',
    'boba fett': 'Sneaky_Clone_(Boba_Fett)',
    'sneaky clone': 'Sneaky_Clone_(Boba_Fett)',
    'boba': 'Sneaky_Clone_(Boba_Fett)',
    'fett': 'Sneaky_Clone_(Boba_Fett)',
    'zoro': 'MossHead_(Zoro)',
    'mosshead': 'MossHead_(Zoro)',
    'nami': 'Cat_Burglar_(Nami)',
    'cat burglar': 'Cat_Burglar_(Nami)',
    'luke skywalker': 'Peaceful_Jedi_(Luke_Skywalker)',
    'skywalker': 'Peaceful_Jedi_(Luke_Skywalker)',
    'luke': 'Peaceful_Jedi_(Luke_Skywalker)',
    'peaceful jedi': 'Peaceful_Jedi_(Luke_Skywalker)',
    'goku': 'Carrot_(Goku)',
    'carrot': 'Carrot_(Goku)',
    'sanji': 'Curly_Brows_(Sanji)',
    'curly brows': 'Curly_Brows_(Sanji)',
    'naruto': 'Nirito_(Naruto)',
    'nirito': 'Nirito_(Naruto)'
}
